### ISSUE TITLE
Alter neural net training data spectrogram script to divide into chunk-based folder hierarchy. Also: use stutter transcript to place spectrograms into stutter-based folder hierarchy.

### ISSUE THREAD

**Issue by s4ayub** [s4ayub/fydp#16]

**Comment by HarminderLall** [comment]
Just FYI folder structure: 

- Stutter A 
         - Sequence one, [Sequence = all spectograms from 4 second clip] 
         - Sequence two 
         - ...
- Stutter B 
         - Sequence one, [Sequence = all spectograms from 4 second clip] 
         - Sequence two 
         - ...
- Stutter C
         - Sequence one, [Sequence = all spectograms from 4 second clip] 
         - Sequence two 
         - ...
- No Stutter 
         - Sequence one, [Sequence = all spectograms from 4 second clip] 
         - Sequence two 
         - ...
